### ISSUE TITLE
Not able to connect if there is a space in attribute id

### ISSUE THREAD

**Issue by gkamle** [jfmdev/jqSimpleConnect#4]
Hi,
If there is space in id then connection is not hapening. Any help on this.
```
<div style="position:relative; height: 80px;">
    <div id="div_a" style="position:absolute; top:5px; left:5px;">Div A</div>
    <div id="div b" style="position:absolute; top:50px; left:150px;">Div B</div>
</div>
<script type="text/javascript">
    jqSimpleConnect.connect("#div_a", "#div b", {radius: 8, color: 'green'});
</script>
```

Kindly help on this.

Thanks,
Govardhan

**Comment by jfmdev** [comment]
Hi Govardhan,

That's not a bug, that's a feature 😄 : spaces aren't allowed (in neither HTML 4 nor HTML 5) in the "id" attribute.

> The HTML 4.01 spec states that ID tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens (-), underscores (_), colons (:), and periods (.). For the class attribute, there is no such limitation. Classnames can contain any character, and they don’t have to start with a letter to be valid.
>
> HTML5 gets rid of the additional restrictions on the id attribute. The only requirements left — apart from being unique in the document — are that the value must contain at least one character (can’t be empty), and that it can’t contain any space characters.
>
> Source: https://stackoverflow.com/a/6802804
