### ISSUE TITLE
Inconsistency in join line width

### ISSUE THREAD

**Issue by SwapnilK15** [jfmdev/jqSimpleConnect#5]
When there are multiple join lines and if browser window is zoom in/out then join lines width varies, so need solution to make then consistent even after zoom in/out

![joinissue](https://user-images.githubusercontent.com/67270880/85284475-e48c5c80-b4ac-11ea-9061-753dde9ddf72.png)

**Comment by jfmdev** [comment]
Hi @SwapnilK15,

In that case you should listen to zoom/resize events, and then call the [repaint](https://github.com/jfmdev/jqSimpleConnect#jqsimpleconnectrepaintconnection) or [repaintall](https://github.com/jfmdev/jqSimpleConnect#jqsimpleconnectrepaintall) functions.

Something like:

```javascript
$(window).resize(function() { 
    jqSimpleConnect.repaintAll(); 
});
```
