### ISSUE TITLE
Connections did not appear when using html2pdf

### ISSUE THREAD

**Issue by karina0866** [jfmdev/jqSimpleConnect#6]
Hello, I was trying to save the drawing into pdf file by using html2pdf. However the connections were disappeared. 
Do you have any idea to solve this issue? 
Thank you

**Comment by jfmdev** [comment]
Hi @karina0866, I'm not very familiar with **html2pdf** but I guess it may be related to the page being converted to PDF before the JavaScript code has been executed.

I found a question on StackOverflow about someone that had a similar issue (although I'm not sure how they solve it): https://stackoverflow.com/questions/36480697/how-force-page-to-wait-for-angular-html2pdf-it-does-not-render-angularjs
